package hunger.hunger.utilities

import org.bukkit.Material

val DISTANCE_BETWEEN_IN_CHUNKS = 6
val ALLOWED_DISTANCE_TO_BASE = 16.0
val DATAWORLD_NAME = "DATAWORLD_HUNGER_PLUGIN"
val UNCAPTURED_BASE_MATERIAL = Material.SEA_LANTERN