package hunger.hunger.dataManaging

import org.bukkit.Material

val DISTANCE_BETWEEN_IN_CHUNKS = 6
val ALLOWED_DISTANCE_TO_BASE = 16.0
val UNCAPTURED_BASE_MATERIAL = Material.SEA_LANTERN
val LOGIC_SERVER_ACCESS_TOKEN = "SECURE_TOKEN_L"
val LOGIC_SERVER_URL = "http://0.0.0.0:2283"
val THIS_SERVER_ACCESS_TOKEN = "SECURE_TOKEN_T"